CREATE TABLE [dbo].[IllegalCharacters](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IllegalWord] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL CONSTRAINT [DF_IllegalCharacters_IsActive]  DEFAULT ((1)),
 CONSTRAINT [PK_IllegalCharacters] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]